# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
theme: jekyll-theme-cayman
# remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/dark.css"
#locale: en-US
locale: es-ES
title: "Droguier's Web v5.666"
description: "Metalwork's index since no JAVA idea from Jekyll"
baseurl: # the subpath of your site, e.g. "/blog"
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax:
  enable: true # MathJax equations, e.g. true, false (default)
  combo: "tex-svg" # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags: "ams" # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "G-WN3DBPQ6GJ"  # Google Analytics id, e.g. "UA-NNNNNNNN-N"
socials:
 - disqus:
    shortname: # Disqus shortname, e.g. "my_disqus_shortname"
 - twitter:
    username: # site's Twitter username, e.g. "mmistakes"

#droguier vars
droguier:
  index: /droguier
  icon: "/assets/icons/favicon.ico"
  skin: "/assets/css/skins/dark.css"
  title: "Droguier's Web v5.666"
  description: "Metalwork page since no JAVA idea from Jekyll"

#florecer vars
florecer:
  index: /florecerterapias
  icon: "/assets/images/florecer/logo_florecer.ico"
  skin: "/assets/css/skins/florecer.css"
  title: "Florecer Terapias"
  description: "Terapeuta del alma, masoterapias y cuidado personal"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /simple/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
#paginate: 10
#paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  #- jekyll-redirect-from

# Collections
collections:
  # Droguier
  droguier:
    output: true
    permalink: /:collection/:title/ 
  # Florecer Terapias 
  florecerpost:
    output: true
    #directory: "_florecerposts"
    permalink: /florecerterapias/publicaciones/:title
  florecergallery:
    output: true
    #directory: "_florecergalley"
    permalink: /florecerterapias/galeria/:title
  florecersvc:
    output: true
    #directory: "_florecergalley"
    permalink: /florecerterapias/serviciosporahora/:title

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true      
  # Recipes
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true   
  # Droguier
  - scope:
      path: "_droguier"
      type: droguier
    values:
      layout: post
      comments: true
      share: true 
  # Florecer Terapias 
  - scope:
      path: "_florecerpost"
      type: florecerpost
    values:
      layout: florecer/post
      comments: true
      share: true
  - scope:
      path: "_florecergalley"
      type: florecergallery
    values:
      layout: florecer/page
      comments: true
      share: true
  - scope:
      path: "_florecersvc"
      type: florecersvc
    values:
      layout: florecer/page
      comments: true
      share: true

# Site Author
author:
  name:
  picture:
  email:
  twitter:
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
