##########################################################################################
### CONFIGURACION DE VARIABLES Y DATOS
##########################################################################################
# site settings
locale                   : "es-ES"
title                    : "Droguier"
tab_subtitle                    : "'s return ver 3.0"
title_separator          : "-"
name                     : &name "Daniel Andres Leiva"
subtitle                 : "'s Web"
email                    : &email "daniel.leiva@ceinf.cl"
description              : &description "Probando un nuevo bootstrap para Jekyll, version de implementación 3.0"
baseurl                  : # the subpath of your site, e.g. "/blog"
url                      : "https://droguier.github.io"
author                   : "Droguier"
street_address           : "Santiago"
city                     : "Santiago"
state                    : "CL"
zip_code                 : "1234567"
country                  : "Chile"
phone                    : "(+56) 9-4177-4655"


### Social Sharing
twitter:
  username               : &twitter "https://twitter.com/echoes_daniel"
facebook:
  username               : #&facebook ""
  app_id                 :
  publisher              :
og_image                 : "site-logo.png" # Open Graph/Twitter default site image
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/echoes_daniel"
    #- "https://facebook.com/michaelrose"

### Site Author
author:
  name             : *name
  avatar           : "echoes_perfil.jpg"
  bio              : "Estudiante de por vida."
  location         : "Santiago, Chile"
  email            : *email
  uri              : "https://droguier.github.io"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : *facebook
  foursquare       :
  github           : "droguier"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    : 5158839/daniel-leiva # http://stackoverflow.com/users/123456/username
  steam            : echoes_cs
  tumblr           :
  twitter          : *twitter
  vine             :
  weibo            :
  xing             :
  youtube          :

# homepage tiles
tiles-source      : posts # accepts "posts" or "pages"
pages-sources     : pages
tiles-count       : 4

# social settings
500px_url         :
facebook_url      :
github_url        :
gitlab_url        :
googleplus_url    : "https://plus.google.com/u/0/+DanieLinLeiva"
instagram_url     :
linkedin_url      : "https://www.linkedin.com/in/droguier/"
pinterest_url     :
slack_url         :
twitter_url       : *twitter

# build settings
markdown: kramdown

sass:
  style: compressed
