# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node CI

on:
  workflow_dispatch :
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_static:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      if: github.ref == 'refs/heads/master'
      env:
          GH_TOKEN    : ${{ secrets.TOKEN_CUENTA }}
          GH_APELLIDO  : ${{ secrets.STR_APELLIDO }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    #- run:  git --version
    - run: echo "$GH_APELLIDO!"
    # - run:  git config --global credential.https://github.com.username $GH_APELLIDO
    # - run:  git config --global credential.https://github.com.password ${{ secrets.TOKEN_CUENTA }}
    - run: npm ci    
    - run: npm run build
    - run: npm run gitpage
